### ISSUE TITLE
i got and idea

### ISSUE THREAD

**Issue by ShadowGaming100** [ZeroDiscord/Giveaway#1]
Add a command that shows how many giveaways are active in that server pls

Update edit command: You can edit the requirements

When you type g!create old add that the bot shows want to add a role requirements

Can add more than 1 requirements role and more than 1 bypass role

**Comment by ZeroDiscord** [comment]
There are no bypass roles as of now and stuff, doing the list thing

**Comment by ZeroDiscord** [comment]
https://github.com/ZeroDiscord/Giveaway/commit/90b32e79bc1818ff276bbc2c2f09f19485b03225 Done, closing this
