### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'update')

### ISSUE THREAD

**Issue by Jarad999** [ZeroDiscord/Giveaway#11]
im using Node.js v17.0.1 & ubuntu 20.04 LTS

**Comment by ZeroDiscord** [comment]
Needs additional log output, stack trace, where the error is originating from. 
CNR. 
Sys details:
Ubuntu 21.04 LTS 
Node v16.x

**Comment by rufy545** [comment]
Yo, I didnt try it yet but I saw that you arent using a db, what will happen in there are giveaways in the queue and the bot goes off

**Comment by ZeroDiscord** [comment]
> Yo, I didnt try it yet but I saw that you arent using a db, what will happen in there are giveaways in the queue and the bot goes off

There are plugins for it within `discord-giveaways` the manager will create a JSON file for it in storage dir called giveaways.json, you may choose to switch your storage to MongoDB, quick.db etcetra, you may refer to the package documentation for such.

**Comment by ZeroDiscord** [comment]
Closing this due to 48 hours of inactivity feel free to add a comment if you think this needs to be reopened.
