### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by Justman10000** [ZeroDiscord/Giveaway#13]
**Describe the bug**
After the successful end of a competition, nobody will be drawn!

**To Reproduce**
Just start a competition and wait for the end

**Expected behavior**
The bot should mention someone in a message stating that they won

**Screenshots**
Is all that changed
![grafik](https://user-images.githubusercontent.com/49990629/140651475-2cf4b7eb-8323-412c-95cd-a51c94882179.png)

**Comment by ZeroDiscord** [comment]
Please check whether that giveaway is present in the database under storage > giveaways.json. please provide the details of the machine you are hosting on.

**Comment by ZeroDiscord** [comment]
inactive

**Comment by Justman10000** [comment]
> 
> 
> inactive

You can't say it's inactive after 3 days!

**Comment by ZeroDiscord** [comment]
Please provide debug details, I'll re-open the issue on that account.

**Comment by Justman10000** [comment]
> 
> 
> Please check whether that giveaway is present in the database under storage > giveaways.json. please provide the details of the machine you are hosting on.

![grafik](https://user-images.githubusercontent.com/49990629/141614200-88fdb842-5047-4333-b227-741fbd159233.png)

[storage > giveaways.json](https://pastebin.com/1vciPajx)

**Comment by Justman10000** [comment]
> 
> 
> Please provide debug details, I'll re-open the issue on that account.

![grafik](https://user-images.githubusercontent.com/49990629/141614200-88fdb842-5047-4333-b227-741fbd159233.png)

[storage > giveaways.json](https://pastebin.com/1vciPajx)

**Comment by ZeroDiscord** [comment]
It's very well there, I assume you maybe corrupted the manager while modifying it if you did? Reinstalling Discord-giveaways might help.

**Comment by Justman10000** [comment]
> 
> 
> It's very well there, I assume you maybe corrupted the manager while modifying it if you did? Reinstalling Discord-giveaways might help.

No, it stays there even after reinstallation!

**Comment by ZeroDiscord** [comment]
Well I'm not sure what's going on here. Is this the first time you're running an instance? It works fine on my end, using galaxygate vps, local machine works fine as well.

**Comment by testbot-github** [comment]
> > Please provide debug details, I'll re-open the issue on that account.
> 
> ![grafik](https://user-images.githubusercontent.com/49990629/141614200-88fdb842-5047-4333-b227-741fbd159233.png)
> 
> [storage > giveaways.json](https://pastebin.com/1vciPajx)

Try emptying the giveaways.json and add this  in that file - 
```[

]```

**Comment by ZeroDiscord** [comment]
> > > Please provide debug details, I'll re-open the issue on that account.
> > 
> > 
> > ![grafik](https://user-images.githubusercontent.com/49990629/141614200-88fdb842-5047-4333-b227-741fbd159233.png)
> > [storage > giveaways.json](https://pastebin.com/1vciPajx)
> 
> Try emptying the giveaways.json and add this in that file -
> 
> ```
> [
> 
> ]
> ```

That would clear the storage hence making the giveaway invalidated.

**Comment by ZeroDiscord** [comment]
Inactive.
