### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by brblacky** [ZeroDiscord/Giveaway#14]
![Screenshot_20211123-102241](https://user-images.githubusercontent.com/77108939/142973122-f885a411-3c44-49dd-b81f-778143afdbce.jpg)
Bug in requirements drop-down

**Comment by ZeroDiscord** [comment]
This means the guild is unavailable to client / uncached you can use optional chaining `?.` to rectify this issue. 
you may also want to fetch the guild instead if you still need the giveaway like so:
```js
 const guild = await client.guilds.fetch(x.extraData.server)
const channel = guild.channels.cache
.filter((channel) => channel.type === 'text')
.first()
```
