### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by brblacky** [ZeroDiscord/Giveaway#15]
create command time out not working

![Screenshot_20211123-210400__01](https://user-images.githubusercontent.com/77108939/143054808-61b4cd89-01cc-424e-abf6-352fc1038704.jpg)

**Comment by ZeroDiscord** [comment]
Will check

**Comment by ZeroDiscord** [comment]
Fixed as of https://github.com/ZeroDiscord/Giveaway/commit/b4306608489963a4b769512dfe6d3566ace0b70a
