### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by ElixorHD** [ZeroDiscord/Giveaway#17]
Hello,

Bot crash when command /help
The crash happens when we make the command twice

Screen1 : https://prnt.sc/21qx8mt
Screen2 : https://prnt.sc/21qxb2t

**Comment by ZeroDiscord** [comment]
Fixed as of https://github.com/ZeroDiscord/Giveaway/commit/a8c2d1e045fa42d8eaaf04943cc53e6b63d386e7

**Comment by ElixorHD** [comment]
Hello,
not work https://prnt.sc/21v34ft

**Comment by ZeroDiscord** [comment]
Are you sure this is on help command

**Comment by ElixorHD** [comment]
Yes command slash

**Comment by ZeroDiscord** [comment]
Try changing it to initialMessage?.send

**Comment by ElixorHD** [comment]
Same when you do the help command twice that crash

**Comment by ElixorHD** [comment]
if we wait for the 30 minutes of time it doesn’t crash anymore.

If we redo the order before the time this crashes

Screenshot of time : https://prnt.sc/22213jn
Screenshot of crash : https://prnt.sc/2221ctp
Screenshot of end time and no crash : https://prnt.sc/2221jeo
