### ISSUE TITLE
[ BUG ] (node:253) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'commands' of undefined

### ISSUE THREAD

**Issue by MashedTuna** [ZeroDiscord/Giveaway#18]
![image](https://user-images.githubusercontent.com/78328022/145775847-fd15e051-905d-43b6-b04e-9bf1c3dd0c99.png)
i downgraded from djs v13 to v12

**Comment by ZeroDiscord** [comment]
Slash commands are not available on discord.js v12 please use [this repository](https://github.com/ZeroDiscord/GiveawayBot) for a discord.js version 12 and a runtime below node.js 16 and above node.js 12.
