### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by JanjyTapYT** [ZeroDiscord/Giveaway#19]
How can I host the bot 24/7? Bc I tryed it but the bot says an error and that the bot needs the node index.js start command but when I change the start command npm start to node index.js then it says to me: "Module not Found" pls help 

And when I use the help command then the bot crashes

**Comment by ZeroDiscord** [comment]
You need to type these commands in order: 

```sh
npm install # this will install all dependencies 
node index.js # or npm start this will start the code 
```
