### ISSUE TITLE
Facing A Issue 

### ISSUE THREAD

**Issue by Teddy-Hokage** [ZeroDiscord/Giveaway#2]
I am having an issue with g!create, when I type none at the end the giveaway doesn't starts. Says Try using g!start instead of having a requirement.
![Screenshot_20210621-130449_1](https://user-images.githubusercontent.com/83545894/122722759-d3c62080-d291-11eb-9934-84d75c1850f8.jpg)

**Comment by Teddy-Hokage** [comment]
You must have fixed but I didn't even changed a letter in that it doesn't work.

**Comment by ZeroDiscord** [comment]
That is intended, when you type `none` I would have to write a code apart from the `extraData` one to start a blank giveaway without requirements, I wanna prevent doing that so I just moved it to -start... Closing this ( I would fix it if I get any collaborators lol )
