### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by JanjyTapYT** [ZeroDiscord/Giveaway#20]
When I run the node index.js command:
![Screenshot_20211217-083210_Firefox](https://user-images.githubusercontent.com/81481526/146506944-d234a942-07d8-41e1-92a4-8de8eaab4688.jpg)
![Screenshot_20211217-083201_Firefox](https://user-images.githubusercontent.com/81481526/146506952-c0b90b84-70f9-4ec2-bc1d-6211247647f4.jpg)

And when I run the npm start command and I use the help command then the bot crashes and goes offline

(Note: I already have installed all with the npm install command)

**Comment by rufy545** [comment]
Not a bug, you need node.js v16

**Comment by ZeroDiscord** [comment]
> Not a bug, you need node.js v16

^
