### ISSUE TITLE
the bot crashes when I use the help command

### ISSUE THREAD

**Issue by JanjyTapYT** [ZeroDiscord/Giveaway#21]
Hello Zero, I installed Node.js v16 but the bot crashes when I usw the help command and the console Shows me that:
![Screenshot_20211219-081359_Firefox](https://user-images.githubusercontent.com/81481526/146667228-d7611831-6ac5-4d12-90e0-471cad6758b2.jpg)

**Comment by ZeroDiscord** [comment]
Bug does not make sense, are you using the command in dms?

**Comment by JanjyTapYT** [comment]
I tryed in dms and in server chat the bot crashes in both chats

**Comment by ZeroDiscord** [comment]
in [`events > discord> messageCreate.js : around line 4`](https://github.com/ZeroDiscord/Giveaway/blob/master/events/discord/messageCreate.js#L4) add 
```js
if(!message?.guild) return 
```
