### ISSUE TITLE
[ HELP ] CHANGE COLOUT

### ISSUE THREAD

**Issue by LOGODERKING** [ZeroDiscord/Giveaway#22]
How can i change the colour of the embed message?

**Comment by Aim2339** [comment]
In every command file, you can see something like this " .setColor('#FFFFFF')"
Just change the tag to your preferred hex code color and you are done!

[Color picker] https://www.w3schools.com/colors/colors_picker.asp

**Comment by ZeroDiscord** [comment]
> > How can I change the colour of the embed message?
> 
> In every command file, you can see something like this " .setColor('#FFFFFF')" Just change the tag to your preferred hex code colour and you are done!
> 
> [Color picker] https://www.w3schools.com/colors/colors_picker.asp

^ If you are looking to change the base colour of giveaway embeds you can change them when you initialize the manager in index.js!

**Comment by LOGODERKING** [comment]
It doenst work

**Comment by Aim2339** [comment]
> It doenst work

Heh, do you face any error or something?
