### ISSUE TITLE
Reroll doesn't work

### ISSUE THREAD

**Issue by PadawanAmy** [ZeroDiscord/Giveaway#23]
when I try and reroll it just says 
X You have to specify a valid message ID!
I am specifying the message ID

**Comment by ZeroDiscord** [comment]
Please do specify the input you are using and verify its availability to the database, update me on this

**Comment by rufy545** [comment]
Can you add more things on the giveaway list commands? Like if there are more than 10 active giveaways the bot will add some buttons like ◀️ ▶️

**Comment by ZeroDiscord** [comment]
> Can you add more things on the giveaway list command? Like if there are more than 10 active giveaways the bot will add some buttons like ◀️ ▶️

Please open a new issue as feature request
