### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by FateDevCode** [ZeroDiscord/Giveaway#26]
![Screenshot_20220211_151157](https://user-images.githubusercontent.com/91865337/153551264-4183da70-ba4f-4a7b-834b-bb60124c39f3.jpg)

They can use the giveaway without perms, and even tho i cancelled the creation of the giveaway thing comes up ^^^

**Comment by ZeroDiscord** [comment]
https://github.com/ZeroDiscord/Giveaway/commit/3ef3e657ba42a0970de94fc4d79c24005fd655c3 Fixed
