### ISSUE TITLE
Discord bot restart bug

### ISSUE THREAD

**Issue by Dominiqos** [ZeroDiscord/Giveaway#3]
https://drive.google.com/file/d/1STvO7Yb1jxseEe-yxpNEJI8xiJfuB_FS/view?usp=drivesdk
Link to video with proof. After restart bot does not recognize giveaways

**Comment by ZeroDiscord** [comment]
I recognize it to be a server requirement giveaway with you not being present in the server, if the bot does not recognize the giveaway it won't remove the reaction, if you are still facing this issue I request you to join the **[Support Server](https://discord.gg/ARu4hr6hJw)** direct message me on discord with the details, I am `0_0#6666`, closing this issue.
