### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by ImSe4n** [ZeroDiscord/Giveaway#31]
**Describe the bug**
I am merging Giveaway with on of my discord bots and I keep on getting the error "RangeError [EMBED_FOOTER_TEXT]: MessageEmbed footer text must be a string." Why is this happening? I have tried using the original Giveaway bot without merging and I get the error "RangeError [EMBED_AUTHOR_NAME]: MessageEmbed author name must be a string." This happens when I use Slash Commands and happens when I use the bonusrole, roleamount, role, and invite options. Please fix it 🙏 

**Screenshots**
My bot:
![image](https://user-images.githubusercontent.com/81334381/159037082-a2471b86-5881-4845-b822-1a07ed61687a.png)

Giveaway bot:
![image](https://user-images.githubusercontent.com/81334381/159037386-1ec44501-50ce-40a9-8f20-b4686cfedba1.png)

**Comment by ZeroDiscord** [comment]
What discord.js version are you running

**Comment by ImSe4n** [comment]
discord.js ^13.1.0

**Comment by ImSe4n** [comment]
I fixed it! I switched to ^13.6.0
