### ISSUE TITLE
[ Feature Request ] Giveaway List

### ISSUE THREAD

**Issue by NotSoMik** [ZeroDiscord/Giveaway#32]
Hello, I got an idea about the giveaway list command, instead of drowpdown menu can you add the buttons? so you can move through all the giveaways

**Comment by AcedDown** [comment]
You can add that yourself by adding a command parsing **Giveaways.json** in it.

**Comment by ZeroDiscord** [comment]
It's already present as a drop-down menu, PRs are appreciated so you may wish to code it on your own and submit a PR, upon review if it's better than what we have here rn you'd be accepted as a contributor 💪😇 gl
