### ISSUE TITLE
Reroll command is not working

### ISSUE THREAD

**Issue by AcedDown** [ZeroDiscord/Giveaway#33]
Hello there,

I am facing this issue where when you try to reroll a giveaway (that exists in the database) it says:

**Unable to find a giveaway for 969403160626094081** (which is a valid giveaway's message id)

Please respond to me ASAP, thank you so much.

**Comment by ZeroDiscord** [comment]
Please make sure the giveaway is in the database, if you're using a host such as glitch or Replit, json and sqlite files are often flushed in them for some particular reason for which details can be found in their support servers, i recommend some other hosting if that's the case and you wish to use the bot for a prolonged period.

**Comment by ZeroDiscord** [comment]
Inactive
