### ISSUE TITLE
[ Feature Request ] Restart Giveaways

### ISSUE THREAD

**Issue by AcedDown** [ZeroDiscord/Giveaway#34]
Just got this idea thanks to my mostly-being-useless brain;

Anyways so apparently I suggest you that you add a command that you can use to restart a certain ended giveaway:
Ex: **.restart <message-id> <default/channel-duration-winners-prize>**

**Default** as for if you want the giveaway to be restarted with the same setup as before.
Ex: **.restart 123456789123456 default**

**channel-duration-winners-prize** Things that need to be filled separated by -
Ex: **.restart 123456789123456 #channel-1m-1-nitro**

**Comment by ZeroDiscord** [comment]
Similar to the .edit command which already has an addTime property one can edit an ended giveaway iirc
