### ISSUE TITLE
[ BUG ] list command dropdown error

### ISSUE THREAD

**Issue by sandarutharuneth** [ZeroDiscord/Giveaway#35]
can't use the **Guild Requirement Giveaways** dropdown option. after using that option bot crashed and stopped.

This is the error

`/home/runner/IVON/slash/list.js:65
                  const channel = guild.channels.cache
                                        ^

TypeError: Cannot read properties of undefined (reading 'channels')
    at /home/runner/IVON/slash/list.js:65:41
    at Array.map (<anonymous>)
    at InteractionCollector.<anonymous> (/home/runner/IVON/slash/list`

**Comment by ZeroDiscord** [comment]
The guild may not be cached i request you to run a `.fetch()` instead or just eval 

```js
client.guilds.cache.get()
```
Which should cache all the guilds by default
