### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by devadicodez** [ZeroDiscord/Giveaway#36]
I'm trying to merge the giveaway with my bot but it shows error in ./utils/message.js
even I've created the file already
![image](https://user-images.githubusercontent.com/83195554/167859245-7ca38493-64a9-4ec3-b777-ee5eeeda1084.png)![image](https://user-images.githubusercontent.com/83195554/167859741-db70cc30-6d53-46cc-b9ef-6935a8d677fe.png)

**Comment by ZeroDiscord** [comment]
You need to check your file structure and add the filepath appropriately, not a bug.
