### ISSUE TITLE
[ BUG ] Permission Bug.. 🐞🐞

### ISSUE THREAD

**Issue by Cupcake-Development** [ZeroDiscord/Giveaway#49]
**Issue:**
Whenever im creating a giveaway using slash command im getting permission error and bot got restarted..

**Console Log**
rawError: { message: 'Missing Permissions', code: 50013 },
  code: 50013,
  status: 403,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/903265280631902229/messages'
}...

**I have these permissions:**
[Attachment 1](https://user-images.githubusercontent.com/84448487/212469589-f8f9c99f-b956-4522-93ad-1a0eb8ef282e.jpg)

How can i resolve this permissions issue?

**Comment by Cupcake-Development** [comment]
Other commands working fine like /help etc.. Just happening with /start command..

**Comment by Aim2339** [comment]
Probably because the bot doesn't have the required ``SEND_MESSAGES``
permission in that particular channel.

**Comment by Aim2339** [comment]
Use some code tpo check if it has the required permission or just catch() it

**Comment by eksekjut** [comment]
It is trying to send a message to a channel and it is missing the 'SEND_MESSAGES' permission.
To fix this issue, you will need to give your bot the necessary permissions in the channel you want it to send messages to. To do this, you will need to navigate to the server settings for the server the bot is a member of and find the 'Roles' or 'Permissions' section. From there, you can add the necessary permissions to the role that your bot has been assigned.

**Comment by ZeroDiscord** [comment]
Inactive.

This is a self-deployed, custom permission simulated instance, cases like these are repairable by playing around with discord permissions, not a code related issue.

Please re-open if bug persists. ( for some reason in code )
